# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f6d06708574e1a3971e38ee06f721f5d151de7bf02f646b6e57dbee75399afe3646bcd262e6752dfa412b005c7bddc5bd4c7e0ee9dba070e7464095dd9d8c1

test:
  secret_key_base: e193ffd7d3e47a223c5adfcbe83d09b4f03568db4fc2ae478090f172e725091c2436199f5d929b4f1c5b03e8f8c7b5b27a01b20769c6c6135fc30d43c5abbeab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
